# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 02:43
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models

import app.models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='_name_choices_str',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=app.models.CustomTreeManyToManyField(blank=True, to='app.Category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_updated',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=app.models.CustomTreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                  to='app.Category'),
        ),
    ]
