# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-04 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_generate_categories__name_choices_str_field_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleDigest',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
            },
            bases=('app.article',),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Processed'),
        ),
    ]
